# `ipython`
> Set of utility functions to be used in Jupyter and Jupyter Lab notebooks.

In [ ]:
#|default_exp ipython

In [ ]:
#| export
from __future__ import annotations
from fastcore.test import test_fail
from functools import wraps
from IPython.core.getipython import get_ipython
from IPython.display import display, Markdown, display_markdown
from pathlib import Path
from typing import Any, List, Callable, Optional, Union
from eccore.core import safe_path, path_to_parent_dir, is_type, CurrentMachine

import numpy as np
import pandas as pd
import sys
import subprocess
import warnings

In [ ]:
#| hide
from nbdev import show_doc, nbdev_export

# System and CLI

In [ ]:
#| export

# TODO: replace with fastcore run

def run_cli(cmd:str = 'ls -l'   # command to execute in the cli
           ):
    """Runs a cli command from jupyter notebook and print the shell output message
    
    Uses subprocess.run with passed command to run the cli command"""
    p = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True)
    print(str(p.stdout, 'utf-8'))

In [ ]:
run_cli('pwd')

/home/vtec/projects/ec-packages/eccore/nbs-dev

# Notebook setup

To be updated using fastcore functions, incl. `walk`, `in_notebook`, ...

In [ ]:
#| export

def nb_setup(
    autoreload:bool = True,       # True to set autoreload in this notebook
    paths: list[Union[str,Path]] = None   # Paths to add to the path environment variable
    ):
    """Use in first cell of notebook to set autoreload, and add system paths
    
    Always add a path to the directoruy 'src' if `srs` directory exists at the same level as the `nbs` directory.

    When the notebook is not located in a tree including the name `nbs`, `src` directory is searched at the same level
    as the directory in which the notebook is located.
    """
    #  Handle paths
    #  Add src if it exists
    nbs_root = path_to_parent_dir('nbs')
    p2src = (nbs_root / '../src').resolve().absolute()
    if p2src.is_dir():
        p = str(p2src.absolute())
        if p not in sys.path:
            sys.path.insert(0, p)
            print(f"Added path: {p2src.absolute()}")
    # Add passed paths
    if paths:
        for p in paths:
            if isinstance(p, Path): p = str(p.resolve().absolute())
            if p not in sys.path:
                sys.path.insert(1, p)
                print(f"Added path: {p}")

#   Setup auto reload
    if autoreload:
        ipshell = get_ipython()
        ipshell.run_line_magic('load_ext',  'autoreload')
        ipshell.run_line_magic('autoreload', '2')
        print('Set autoreload mode')

In [ ]:
show_doc(nb_setup)

def nb_setup(
    autoreload:bool=True, # True to set autoreload in this notebook
    paths:list[Union[str, Path]]=None, # Paths to add to the path environment variable
):"""Use in first cell of notebook to set autoreload, and add system paths

Always add a path to the directoruy 'src' if `srs` directory exists at the same level as the `nbs` directory.

When the notebook is not located in a tree including the name `nbs`, `src` directory is searched at the same level
as the directory in which the notebook is located."""

By default, `ipython.nb_setup()` 
- loads and set `autoreload`
- adds a path to a directory named `src` when it exists at the same level as where the notebook directory is located. It no such `src` directory exists, no path is added

`ipython.nb_setup` assumes the following file structure:

```
    project_directory
          |--- nbs
          |     | --- current_nb.ipynb
          |     | --- ...
          |
          |--- src
          |     | --- module_to_import.py
          |     | --- ...
          |
          |--- data
          |     |
          |     | ...
```

For other file structure, specify paths as a `list` of `Path`

Before running `nb_setup`, `sys.path` does not include the path to the local source directory. After running it, it will be added, unless the directory does not exist.

In [ ]:
sys.path

['/home/vtec/miniconda3/envs/eccore/lib/python313.zip',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13/lib-dynload',
 '',
 '/home/vtec/.local/lib/python3.13/site-packages',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13/site-packages',
 '/home/vtec/projects/ec-packages/eccore']

In [ ]:
nb_setup(autoreload=False)

Added path: /home/vtec/projects/ec-packages/eccore/src

In [ ]:
sys.path

['/home/vtec/projects/ec-packages/eccore/src',
 '/home/vtec/miniconda3/envs/eccore/lib/python313.zip',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13/lib-dynload',
 '',
 '/home/vtec/.local/lib/python3.13/site-packages',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13/site-packages',
 '/home/vtec/projects/ec-packages/eccore']

We also can add other specific paths:

In [ ]:
path_to_add = str(Path('../nbs').resolve().absolute())
nb_setup(autoreload=False, paths=[path_to_add])

Added path: /home/vtec/projects/ec-packages/eccore/nbs

In [ ]:
sys.path

['/home/vtec/projects/ec-packages/eccore/src',
 '/home/vtec/projects/ec-packages/eccore/nbs',
 '/home/vtec/miniconda3/envs/eccore/lib/python313.zip',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13/lib-dynload',
 '',
 '/home/vtec/.local/lib/python3.13/site-packages',
 '/home/vtec/miniconda3/envs/eccore/lib/python3.13/site-packages',
 '/home/vtec/projects/ec-packages/eccore']

In [ ]:
#| export
def install_code_on_cloud(
    package_name:str, # project package name, e.g. metagentools or git+https://github.com/repo.git@main
    quiet:bool=False # install quietly with Trud
):
    """pip install the project code package, when nb is running in the cloud."""
    
    machine = CurrentMachine()

    if machine.is_colab:
        CLOUD = True
        print('The notebook is running on colab.', end=' ')
        print(f'Will install {package_name}')
    elif machine.is_kaggle:
        CLOUD = True
        print('The notebook is running on kaggle.', end=' ')
        print(f'Will install {package_name}')
    elif machine.is_local:
        CLOUD = False
        print('The notebook is running locally, will not automatically install project code')
    else:
        CLOUD = True
        print('The notebook is running on a cloud VM or the machine was not registered as local')
        print(f'Will install {package_name}')

    if CLOUD:
        print(f'Installing project code {package_name}')
        cmd = f"pip install -{'qq' if quiet else ''}U {package_name}"
        run_cli(cmd)
        print((f"{package_name} is installed."))

In [ ]:
show_doc(install_code_on_cloud)

def install_code_on_cloud(
    package_name:str, # project package name, e.g. metagentools or git+https://github.com/repo.git@main
    quiet:bool=False, # install quietly with Trud
):"""pip install the project code package, when nb is running in the cloud."""

When using colab, kaggle or another cloud VM, specicif code must be installed every time from the Python Package Index (PyPI) or its GitHub repo.

When running locally, the project code should be pre-installed as part of the environment

In [ ]:
install_code_on_cloud(package_name='metagentools');

The notebook is running locally, will not automatically install project code

# Improve output cell formats

In [ ]:
#| export

# TODO: Migrate display_mds to printmd

def display_mds(
    *strings:str|tuple[str] # any number of strings with text in markdown format
):
    """Display one or several strings formatted in markdown format"""
    for string in strings:
        display_markdown(Markdown(data=string))

In [ ]:
show_doc(display_mds)

def display_mds(
    *strings:str | tuple[str], # any number of strings with text in markdown format
):"""Display one or several strings formatted in markdown format"""

In [ ]:
display_mds('**bold** and _italic_')

**bold** and _italic_

In [ ]:
display_mds('**bold** and _italic_',
            '- bullet',
            '- bullet',
            '> Note: this is a note'
)

**bold** and _italic_

- bullet

- bullet

> Note: this is a note

In [ ]:
#| export
def display_dfs(*dfs:pd.DataFrame       # any number of Pandas DataFrames
               ):
    """Display one or several `pd.DataFrame` in a single cell output"""
    for df in dfs:
        display(df)

In [ ]:
show_doc(display_dfs)

def display_dfs(
    *dfs:pd.DataFrame, # any number of Pandas DataFrames
):"""Display one or several `pd.DataFrame` in a single cell output"""

In [ ]:
df1 = pd.DataFrame(data=np.random.normal(size=(10,5)))
df2 = pd.DataFrame(data=np.random.normal(size=(20,10)))

display_dfs(df1.head(3), df2.head(3))

          0         1         2         3         4
0 -0.488617  0.002937 -0.831025 -0.678964 -0.521797
1 -0.447557 -2.551089  1.325671  1.872702  1.300323
2 -1.311307 -0.556721  0.665384 -0.808619  3.151739

,0,1,2,3,4,5,6,7,8,9
0,-0.676528,0.303777,0.988493,-0.292007,0.817056,1.654942,0.043613,-0.120780,-0.465421,1.760659
1,1.415112,-1.401976,-1.241060,-1.518592,-0.075591,-0.358521,0.448668,-0.016183,-0.067024,0.630555
2,0.426779,-0.969347,2.815433,-0.855414,0.969142,0.848690,-1.004748,0.656167,0.146389,1.167223

In [ ]:
#| export
class pandas_nrows_ncols:
    """Context manager that sets the max number of rows and cols to apply to any output within the context"""
    def __init__(
        self, 
        nrows:int|None=None, # max number of rows to show; show all rows if `None`
        ncols:int|None=None, # max number of columns to show; show all columns if `None`
    ):
        self.nrows = nrows
        self.ncols = ncols
    
    def __enter__(self):
        self.max_rows = pd.options.display.max_rows
        self.max_cols = pd.options.display.max_columns
        pd.options.display.max_rows = self.nrows
        pd.options.display.max_columns = self.ncols
        return self.max_rows, self.max_cols

    def __exit__(self, exc_type, exc_value, exc_tb):
        pd.options.display.max_rows = self.max_rows
        pd.options.display.max_columns = self.max_cols

In [ ]:
show_doc(pandas_nrows_ncols)

def pandas_nrows_ncols(
    nrows:int | None=None, # max number of rows to show; show all rows if `None`
    ncols:int | None=None, # max number of columns to show; show all columns if `None`
):"""Context manager that sets the max number of rows and cols to apply to any output within the context"""

With no context manager, the pandas object are displayed with a maximum of 60 rows and 20 columns.

In [ ]:
df = pd.DataFrame(np.random.randint(low=0, high=100, size=(3,50)))
display(df)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,4,42,52,30,61,90,38,76,77,33,...,98,63,92,44,75,38,41,9,52,80
1,16,38,78,96,47,42,94,39,60,24,...,69,58,20,23,52,15,22,29,81,88
2,22,85,78,41,45,57,46,58,88,99,...,92,34,11,54,70,19,20,41,63,33

Using the context manager, all rows and columns will be displayed

In [ ]:
with pandas_nrows_ncols():
    display(df)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,4,42,52,30,61,90,38,76,77,33,58,56,85,89,47,89,0,45,84,81,97,97,85,44,69,41,1,62,57,83,52,59,61,22,16,13,81,56,72,57,98,63,92,44,75,38,41,9,52,80
1,16,38,78,96,47,42,94,39,60,24,84,15,62,7,69,58,77,18,16,98,8,1,44,76,57,13,56,61,65,52,57,41,26,3,95,2,71,13,91,45,69,58,20,23,52,15,22,29,81,88
2,22,85,78,41,45,57,46,58,88,99,73,36,93,64,37,87,44,17,83,50,55,31,86,8,73,91,18,67,47,54,41,74,36,82,77,32,13,3,85,59,92,34,11,54,70,19,20,41,63,33

It is also possible to specifically define the number of rows and columns to display

In [ ]:
with pandas_nrows_ncols(nrows=2, ncols=6):
    display(df)

    0   1   2   ...  47  48  49
0    4  42  52  ...   9  52  80
..  ..  ..  ..  ...  ..  ..  ..
2   22  85  78  ...  41  63  33

[3 rows x 50 columns]

In [ ]:
with pandas_nrows_ncols(2,6):
    print(df)

    0   1   2   ...  47  48  49
0    4  42  52  ...   9  52  80
..  ..  ..  ..  ...  ..  ..  ..
2   22  85  78  ...  41  63  33

[3 rows x 50 columns]

> ### Technical background
> 
> the context manager uses pandas's [`options API`](https://pandas.pydata.org/docs/user_guide/options.html)

In [ ]:
pd.options.display.max_rows, pd.options.display.max_columns

(60, 20)

In [ ]:
pd.get_option('display.max_rows'), pd.get_option('display.max_columns')

(60, 20)

In [ ]:
pd.describe_option('display.max_rows')

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]

In [ ]:
pd.options.display.max_rows = 10
pd.reset_option('display.max_rows')
pd.options.display.max_rows

60

In [ ]:
#| export
def display_full_df(
    df:pd.DataFrame|pd.Series,  # `DataFrame` or `Series` to display
):
    """Display a pandas `DataFrame` or `Series` showing all rows and columns"""
    if is_type(df, pd.DataFrame, raise_error=False) or is_type(df, pd.Series, raise_error=False):
        with pandas_nrows_ncols():
            display(df)
    else:
        raise TypeError(f"df must me a pandas `DataFrame` or `Series`, not a {type(df)}")

In [ ]:
show_doc(display_full_df)

def display_full_df(
    df:pd.DataFrame | pd.Series, # `DataFrame` or `Series` to display
):"""Display a pandas `DataFrame` or `Series` showing all rows and columns"""

In [ ]:
df = pd.DataFrame(np.random.randint(low=0, high=100, size=(3,50)))
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,30,84,57,4,26,19,21,43,42,9,...,45,50,15,52,11,39,58,90,25,13
1,40,27,7,69,31,16,94,43,47,76,...,92,18,94,92,96,77,91,71,6,74
2,0,2,58,32,25,4,20,64,49,48,...,91,82,64,59,21,24,64,66,69,67

In [ ]:
display_full_df(df)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,30,84,57,4,26,19,21,43,42,9,11,86,35,69,33,42,25,85,2,12,3,39,32,16,88,87,96,37,1,28,78,0,21,96,76,3,76,44,48,89,45,50,15,52,11,39,58,90,25,13
1,40,27,7,69,31,16,94,43,47,76,15,68,31,72,7,91,35,82,81,85,77,31,13,60,29,18,29,58,44,91,58,69,42,2,10,19,34,5,6,96,92,18,94,92,96,77,91,71,6,74
2,0,2,58,32,25,4,20,64,49,48,41,68,31,21,26,17,54,97,61,74,5,86,34,71,71,84,94,51,73,72,43,31,29,27,73,40,8,85,87,66,91,82,64,59,21,24,64,66,69,67

In [ ]:
#| hide
display_full_df(df.loc[0, :].T)

0     30
1     84
2     57
3      4
4     26
5     19
6     21
7     43
8     42
9      9
10    11
11    86
12    35
13    69
14    33
15    42
16    25
17    85
18     2
19    12
20     3
21    39
22    32
23    16
24    88
25    87
26    96
27    37
28     1
29    28
30    78
31     0
32    21
33    96
34    76
35     3
36    76
37    44
38    48
39    89
40    45
41    50
42    15
43    52
44    11
45    39
46    58
47    90
48    25
49    13
Name: 0, dtype: int64

In [ ]:
msg = 'should raise a TypeError'
contains = 'df must me a pandas `DataFrame` or `Series`'

test_fail(display_full_df, args=['a string'], msg=msg, contains=contains)

In [ ]:
#| hide
nbdev_export()